query getUserDataQuery($userEmail: StringFilterInput) {
    usersPermissionsUsers(filters: { email: $userEmail }) {
        data {
            id
            attributes {
                email
                username
                cart
            }
        }
    }
}
