query Footer {
    footer {
        data {
            attributes {
                FooterBrand {
                    id
                    FooterLogotype {
                        data {
                            attributes {
                                url
                            }
                        }
                    }
                    FooterCopyright
                }
                FooterNavLists {
                    ListName
                    FooterLink {
                        LinkName
                        LinkURL
                    }
                }
            }
        }
    }
}
