query Header {
    header {
        data {
            id
            attributes {
                Logotype {
                    data {
                        attributes {
                            url
                        }
                    }
                }
                PageName
                Navigation {
                    id
                    Link {
                        id
                        LinkName
                        LinkURL
                    }
                    LoginButton {
                        id
                        ButtonIcon {
                            data {
                                attributes {
                                    url
                                }
                            }
                        }
                        ButtonText
                        ButtonStyle
                        ButtonLink
                    }
                    CartButton {
                        id
                        CartIcon {
                            data {
                                attributes {
                                    url
                                }
                            }
                        }
                    }
                    MobileButton {
                        id
                        MobileButtonIcon {
                            data {
                                attributes {
                                    url
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
